# -*- coding: utf-8 -*-
"""coventry_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQhNmbjXOTCCTcTW6uzDLQEpS_kdedsd
"""

# Import libraries
import requests
from bs4 import BeautifulSoup
import json
import re

# Required schema fields (as per assignment)
required_fields = [
    "program_course_name",
    "university_name",
    "course_website_url",
    "campus",
    "country",
    "address",
    "study_level",
    "course_duration",
    "all_intakes_available",
    "mandatory_documents_required",
    "yearly_tuition_fee",
    "scholarship_availability",
    "gre_gmat_mandatory_min_score",
    "indian_regional_institution_restrictions",
    "class_12_boards_accepted",
    "gap_year_max_accepted",
    "min_duolingo",
    "english_waiver_class12",
    "english_waiver_moi",
    "min_ielts",
    "kaplan_test_of_english",
    "min_pte",
    "min_toefl",
    "ug_academic_min_gpa",
    "twelfth_pass_min_cgpa",
    "mandatory_work_exp",
    "max_backlogs"
]

# Create default data dictionary
def create_empty_data():
    return {key: "NA" for key in required_fields}

import requests
from bs4 import BeautifulSoup
import json
import re

# Function to get course links

def get_course_links():
    url = "https://www.coventry.ac.uk/search/?search=&contentType=newcoursepage&sl=140_"
    headers = {"User-Agent": "Mozilla/5.0"}

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    links = set()

    for a in soup.find_all("a", href=True):
        href = a["href"]

        # Filter only undergraduate course links
        if "/course-structure/ug/" in href:
            if href.startswith("/"):
                href = "https://www.coventry.ac.uk" + href

            links.add(href)

    return list(links)



# Function to scrape course data

def scrape_course(url):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    data = create_empty_data()

    # Static fields
    data["course_website_url"] = url
    data["university_name"] = "Coventry University"
    data["country"] = "UK"
    data["study_level"] = "Undergraduate"

    # Extract course name
    title = soup.find("h1")
    if title:
        data["program_course_name"] = title.get_text(strip=True)

    # Extract page text
    page_text = soup.get_text(separator=" ").lower()

    # Extract duration (e.g., 3 years)
    duration_match = re.search(r"\b\d+\s+year[s]?\b", page_text)
    if duration_match:
        data["course_duration"] = duration_match.group()

    # Extract intake
    if "september" in page_text:
        data["all_intakes_available"] = "September"

    # Extract IELTS score
    ielts_match = re.search(r"ielts.*?(\d\.\d)", page_text)
    if ielts_match:
        data["min_ielts"] = ielts_match.group(1)

    # Extract tuition fees (last value assumed international fee)
    # Updated regex to capture numbers with commas and optional spaces after £
    fee_matches = re.findall(r"£\s*([\d,]+)", page_text)
    if fee_matches:
        # Get the last match, remove commas, and prefix with £
        cleaned_fee = "£" + fee_matches[-1].replace(",", "")
        data["yearly_tuition_fee"] = cleaned_fee

    # Extract campus
    if "coventry" in page_text:
        data["campus"] = "Coventry"

    return data

print("Fetching course links...")

links = get_course_links()

results = []
seen_courses = set()   # To remove duplicates

for link in links:
    if len(results) == 5:
        break

    print(f"Scraping: {link}")

    try:
        data = scrape_course(link)
        course_name = data["program_course_name"]

        # Remove duplicates based on course name
        if course_name and course_name not in seen_courses:
            results.append(data)
            seen_courses.add(course_name)

    except Exception as e:
        print(f"Error: {e}")

# Save output file
with open("output.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4, ensure_ascii=False)

print("\n✅ Scraping complete!")
print(f"Total unique courses scraped: {len(results)}")